version: '3.8'

services:
  collector:
    build: .
    image: webhook-relay:latest
    command: webhook_relay.collector.app serve --config /config/collector_config.yaml
    ports:
      - "8000:8000"  # API port
      - "9090:9090"  # Metrics port
    volumes:
      - ./examples:/config
    environment:
      - WEBHOOK_RELAY_LOG_LEVEL=INFO
    networks:
      - webhook-net
    restart: unless-stopped

  forwarder-example:
    build: .
    image: webhook-relay:latest
    command: webhook_relay.forwarder.app serve --config /config/forwarder_config.yaml
    ports:
      - "9091:9091"  # Metrics port
    volumes:
      - ./examples:/config
    environment:
      - WEBHOOK_RELAY_LOG_LEVEL=INFO
    networks:
      - webhook-net
    restart: unless-stopped
    depends_on:
      - collector

  # Example of a target service that might receive the forwarded webhooks
  # This is just a placeholder for demonstration
  target-service:
    image: nginx:alpine
    ports:
      - "8080:80"
    networks:
      - webhook-net
    restart: unless-stopped
    volumes:
      - ./examples/nginx-placeholder.conf:/etc/nginx/conf.d/default.conf

networks:
  webhook-net:
    driver: bridge