host: "0.0.0.0"
port: 8000
log_level: "INFO"
queue_type: "gcp_pubsub"  # or "aws_sqs"

# GCP PubSub configuration (if queue_type is "gcp_pubsub")
gcp_config:
  # project_id: "your-gcp-project-id" 
  # or WEBHOOK_RELAY_GCP_CONFIG__PROJECT_ID=your-gcp-project-id
  topic_id: "webhook-relay-topic"

# AWS SQS configuration (if queue_type is "aws_sqs")
# aws_config:
#   region_name: "us-west-2"
#   queue_url: "https://sqs.us-west-2.amazonaws.com/123456789012/webhook-relay-queue"
#   access_key_id: "YOUR_ACCESS_KEY"  # Optional, can use environment variables or instance roles
#   secret_access_key: "YOUR_SECRET_KEY"  # Optional, can use environment variables or instance roles
#   role_arn: "arn:aws:iam::123456789012:role/webhook-relay-role"  # Optional, for assuming an IAM role

metrics:
  enabled: true
  host: "127.0.0.1"
  port: 9090
  path: "/metrics"

webhook_sources:
  - name: "github"
    secret: "your-github-webhook-secret"  # Optional, for signature verification
    signature_header: "X-Hub-Signature-256"  # Header containing the signature
  - name: "gitlab"
    secret: "your-gitlab-webhook-secret"  # Optional
    signature_header: "X-Gitlab-Token"
  - name: "custom"  # A source without signature verification